import React from "react"
import type { Metadata } from "next"
import { Open_Sans } from "next/font/google"
import "./globals.css"
import { InnerLayout } from "./InnerLayout"

const font = Open_Sans({
    subsets: ["latin"],
    weight: ["400", "500", "600", "700"],
})
export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
}

const RootLayout = ({
    children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
    return (
        <html lang="en">
            <body
                className={`${font.className} antialiased`}
            >
                <InnerLayout>{children}</InnerLayout>
            </body>
        </html>
    )
}

export default RootLayout
